build:
  stage: build
  image: ingomuellernet/buildenv
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - cd gen
    - cmake ../src
    - make
  artifacts:
    paths:
      - gen

test:
  stage: test
  image: ingomuellernet/buildenv
  script:
    - cd gen
    - make test CTEST_OUTPUT_ON_FAILURE=1
  dependencies:
    - build

format:
  stage: build
  image: ingomuellernet/buildenv
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - cd gen
    - cmake ../src
    - make check-format
